//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAD_CW2_2017_2018_00004628
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblTransactionItem
    {
        public int TransactionItemID { get; set; }
        public int TransactionID { get; set; }
        public int ProductID { get; set; }
    
        public virtual TblProduct TblProduct { get; set; }
        public virtual TblTransaction TblTransaction { get; set; }
    }
}
